### ISSUE TITLE
Update libgdx version

### ISSUE THREAD

**Issue by dranikpg** [CypherCove/gdx-cclibs#3]
Current version 1.9.7 is outdated

**Comment by cypherdare** [comment]
Thank you. So...I accidentally placed the PC containing my only copy of my keystore in a storage unit buried with stuff I don't intend to retrieve for a couple years. Too painful to dig it out, so I'm debating whether I should create a new repository.

**Comment by cypherdare** [comment]
I've split the three projects so I can independently control the versioning. It was getting difficult to maintain due to more recent SDKs for Java and Android requiring specific versions of Gradle.

The new versions are all updated to LibGDX 1.9.9.
